# Generated by Django 3.0 on 2019-12-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_file1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File1',
        ),
    ]
